# 3
dantmac/VKNewsFeed pull request #3
Opened 2021-06-03 17:56 UTC by dantmac

2021-06-03 18:56 UTC, eugeniusIT requested changes
Left some comments 
Keep attention to:
- Removing all force unwraps 
- Removing all commented code or leaving TODO marks 
- Making code style be consistent (new lines, whitespaces etc)

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Views/WebImageView.swift
> +        let dataTask = URLSession.shared.dataTask(with: url) { [weak self] (data, response, error) in
Consider removing commented code

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Views/GradientView.swift
> +            gradientLayer.colors = [startColor.cgColor, endColor.cgColor]
Consider removing obsolete tab

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Views/GradientView.swift
> +
Consider removing commented code or add TODO mark

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Services/NetworkService.swift
> +       return components.url!
Consider removing force unwrap

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Services/NetworkService.swift
> +        allParams["v"] = API.version
consider moving strings in [] into a separate private enum Configurations with static strings 

```
enum Configuration {
    static string accessTokenKey = "access_token" 
    static string versionKey = "v" 
}
```

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Services/NetworkDataFetcher.swift
> +        var params = ["filters": "post, photo"]
The same comment about filters key into separate enum 

Also consider removing obsolete new line

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Views/WebImageView.swift
> +            return }
consider making

 ```
   return 
}
```

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Services/Models/FeedResponse.swift
> +    var photo: String { return photo100 }
it is not clear why you have duplicate photo fields 

consider removing obsolete photo100 property

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Services/AuthService.swift
> +        print(#function)
is this function needed?
if not, then consider removing it

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/Services/AuthService.swift
> +
I'd recommend removing `print` if you not need them, but its up to you

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/SceneDelegate.swift
>          // Called as the scene is being released by the system.
consider removing unused scene delegate methods

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/SceneDelegate.swift
> +        let NewsFeedVC = UIStoryboard(name: "NewsFeedViewController", bundle: nil).instantiateInitialViewController() as! NewsFeedViewController
I'd recommend replacing force case with optional binding

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/NewsFeedWorker.swift
> +            completion(self!.revealedPostIds, feedResponse)
consider removing force unwraps from this files

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/NewsFeedWorker.swift
> +class NewsFeedService {
I'd recommend adding a protocol for this service

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/NewsFeedViewController.swift
> +
consider removing not needed commented lined

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/NewsFeedViewController.swift
> +
seem to be an unused mark

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/NewsFeedRouter.swift
> +class NewsFeedRouter: NSObject, NewsFeedRoutingLogic {
seem to be an unused file

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/NewsFeedPresenter.swift
> +        return FeedViewModel.Cell.init(postId: feedItem.postId,
I'd recommend using FeedViewModel.Cell(...) instead of FeedViewModel.Cell.init(...) , but its up to you

2021-06-03 18:56 UTC, eugeniusIT commented on VKNewsFeed/NewsFeed/Cell/NewsFeedCodeCell.swift
> +        overlayThirdLayerObBottomView() // the Third layer on bottomView
1 - a type here -  Ob 
2 - the names of functions are quite descriptive, so these comments are obsolete

2021-06-11 17:03 UTC, dantmac commented
made changes after a core review

2021-06-11 17:04 UTC, merged